name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: main
      aws-assume-role-arn: "arn:aws:iam::075180584955:role/github-actions-uriassousa-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "uriassousa-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "uriassousa-us-east-1-terraform-lock"